Repository 25MPOOL/Prism, pull requests merged in 2025-08, with the labels that each got.

#17 apps/extension/ ディレクトリ構成を作成
  apps/extension/components/.keep
  apps/extension/hooks/.keep
  apps/extension/utils/.keep
Labels: 🔥 優先度: 高, 🖥️ フロントエンド

#23 初期セットアップ
  .cursor/rules/prismDocuments.mdc
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/submit.yml
  .gitignore
  .husky/pre-commit
  .vscode/extensions.json
  .vscode/settings.json
  apps/api/.gitignore
  apps/api/README.md
  apps/api/drizzle.config.ts
  apps/api/drizzle/schema.ts
  apps/api/package.json
  apps/api/src/index.ts
  apps/api/src/middleware/.keep
  apps/api/src/routes/.keep
  apps/api/src/services/.keep
  apps/api/src/types/.keep
  apps/api/test/.keep
  apps/api/tsconfig.json
  apps/api/wrangler.jsonc
  apps/extension/.gitignore
  apps/extension/README.md
  apps/extension/assets/icon.png
  apps/extension/package.json
  apps/extension/postcss.config.js
  apps/extension/src/components/.keep
  apps/extension/src/globals.css
  apps/extension/src/hooks/.keep
  apps/extension/src/popup.tsx
  apps/extension/src/utils/.keep
  apps/extension/tailwind.config.js
  apps/extension/tsconfig.json
  biome.json
  package.json
  packages/.keep
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: ⚙️ バックエンド, 🔥 優先度: 高, 🖥️ フロントエンド

#56 GihubActions CICDの実装
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  apps/api/package.json
  package.json
Labels: ⚙️ バックエンド, 🖥️ フロントエンド

#58 Gemini API
  apps/api/drizzle.config.ts
  apps/api/package.json
  apps/api/src/index.ts
  apps/api/src/routes/conversation.ts
  apps/api/src/services/conversationsService.ts
  apps/api/src/services/google/gemini-api.ts
  apps/api/src/types/definitions.ts
  apps/api/src/utils/.keep
Labels: ⚙️ バックエンド

#64 Websocketの実装
  apps/api/src/index.ts
  apps/api/src/routes/websocket.ts
  apps/api/src/services/conversationsService.ts
  apps/api/src/services/google/.keep
  apps/api/src/types/definitions.ts
  pnpm-lock.yaml
Labels: ⚙️ バックエンド, ✨ 新機能

#67 Layoutデザインの実装
  apps/extension/src/components/.keep
  apps/extension/src/components/ChatArea.tsx
  apps/extension/src/components/ChatInput.tsx
  apps/extension/src/sidepanel/AppLayout.tsx
  apps/extension/src/sidepanel/index.html
  apps/extension/src/sidepanel/index.tsx
  apps/extension/tailwind.config.js
  apps/extension/tsconfig.json
  biome.json
  package.json
Labels: 🎨 UI改善, 🖥️ フロントエンド

#80 キーボードショートカットからサイドパネルを表示できるようにしました。
  apps/extension/package.json
  apps/extension/src/background.ts
Labels: ✨ 新機能, 🖥️ フロントエンド

#90 GitHubアカウントでPrismにログインし、その情報を自動で保存するロジックの実装
  apps/api/drizzle.config.ts
  apps/api/drizzle/migrations/0003_majestic_mordo.sql
  apps/api/drizzle/migrations/0004_blushing_shen.sql
  apps/api/drizzle/migrations/meta/0003_snapshot.json
  apps/api/drizzle/migrations/meta/0004_snapshot.json
  apps/api/drizzle/migrations/meta/_journal.json
  apps/api/drizzle/schema.ts
  apps/api/package.json
  apps/api/src/index.ts
  apps/api/src/routes/github.ts
  apps/api/src/services/github/auth.ts
  apps/api/src/services/user.ts
  apps/api/src/types/github.ts
  biome.json
Labels: ⚙️ バックエンド, ✨ 新機能, 🔥 優先度: 高

#99 保存されたトークンの取得とリフレッシュ
  apps/api/src/routes/github.ts
  apps/api/src/services/github/auth.ts
  apps/api/src/services/user.ts
Labels: ⚙️ バックエンド, ✨ 新機能, 🔥 優先度: 高

#100 OAuth認証を拡張機能からできるように実装
  apps/extension/package.json
  apps/extension/src/background.ts
  apps/extension/src/hooks/.keep
  apps/extension/src/hooks/api/useGithubOAuth.ts
  apps/extension/src/sidepanel/index.tsx
  apps/extension/src/utils/.keep
  apps/extension/src/utils/client.ts
  pnpm-lock.yaml
Labels: ✨ 新機能, 🖥️ フロントエンド

#109 GitHub APIを叩いて、リポジトリ一覧を取得する実装
  apps/api/src/routes/github.ts
  apps/api/src/types/github.ts
Labels: ⚙️ バックエンド, ✨ 新機能

#124 リポジトリー選択コンポーネントの実装
  apps/extension/package.json
  apps/extension/src/background.ts
  apps/extension/src/components/SelectRepository.tsx
  apps/extension/src/hooks/api/getRepos.ts
  apps/extension/src/hooks/api/queryKeys.ts
  apps/extension/src/hooks/api/useGithubOAuth.ts
  apps/extension/src/sidepanel/index.tsx
  apps/extension/src/utils/client.ts
  pnpm-lock.yaml
Labels: 🖥️ フロントエンド

#128 GitHubユーザープロファイル情報を取得するエンドポイントを追加
  apps/api/src/routes/github.ts
Labels: ⚙️ バックエンド, ✨ 新機能
